const strs = [
  'PPZTzDhJPLqPhqDTqrwQZZWbmCBMJMcsNmCBFWmMcsNb',
  'vplSlfdfGvfRRGsgNcMglsFWMWMC',
  'jtjvFHdjjwqrwqwL',
  'NSffhsNSjfLjfstsjtjNNjjqMqnpggHngqgHGHCgClGbCzCC',
  'dDPZZDZFdwFWwFZFWZRTFDwGzCMlgnpgCpnzglClHMbg',
  'DTPFZQRcdTVNhbjVbcLc',
  'JZLDcSZSpHHrrLrJcpzBRrhlzgRTmTmvBRmm',
  'qQsQMCbMQWqCVVvmTRhTTRhCRhTg',
  'svbGWPqGPNLJSpZnZpnN',
  'wLtPGCLwfWLflCPtPfLLTSbHMbSgMdtvDHghhHvdgZ',
  'nNsFznJcJqzFFszFqrNnRzdbZDDbRMbMdRHbMdgHvZSd',
  'VczNnjsrFrjcNprqVwTPfjGllWPQBBWlgB',
  'nnGtjFFjFTTTGtBGmWBTWffLcMJMQlzjQPCPcChCQDJzDJJd',
  'SSggbHVbZRgZsHZRHdVhzCcJhzhMzJhQPQ',
  'rHsNSsSZqqrNgpLLWmCfFGqGCBWm',
  'ZnCtCCVZmVBCQBWQnWQNCQMcLrMMgMLqLSwMSSDwjcBD',
  'hTbGJGfTbrSfScmjwj',
  'bbGGlTdlJTdGlFpdFvJdsbmdZWPWtnVCHQvtVHzvtHWtCtVN',
  'pNpCNFMNFhhwDgRVdSVqwgrdmJ',
  'nvHbPZtTHWbntTmdTRrqVRrdmz',
  'vHWPBWvntbWnHLHZLqWtBCjjhBNhCjGjjNjDNChlFC',
  'CnFbFzpzJbsCRpbRpbnPCnJLTtwQtjdtcttHHHDtDPjQwTHB',
  'qGrflmrNgvvmGqcdwrtWQHwTBHQWtj',
  'mVMvSclGqvNVMMNVsZsnJJRJsbzpSJpJ',
  'cJTcRllRldjZlFcbcFJrrvqCCVTNNVWSPpQNmpQqCPVC',
  'wGLBfLzgBfzHGGGnLDGDGgwHqqHmVSWqpQpCpQRWVWVNpS',
  'DRshRBLMhZlFZMJvlJ',
  'SdGbmRGddMcfbWWSptssDHssGDNsjCCC',
  'glPLTzczrCpNNsHTst',
  'gqcZJPrBlhJgPndMVJbWMVfnWV',
  'qNbmLmndBQqjsCPLZsLPZz',
  'pwfhfCvJvvTMGzSjzPSPjcZp',
  'VvvJVMCrvTRwgvwWvqNmqblNHtBWqQWlql',
  'WNJmddmpFmMMrnlFddlWTHCHBRcnCBTRzTDRTwTz',
  'qffLvLLvbqhqPbjbqRGPSqVtPDTTwTwTDzCBCccQczssCwcc',
  'tfhGLhqthZVhbfpFRJMMMrJrZpmZ',
  'VVgSmdqFpMddqSfpfVVWQvzTPvTWPrpsQPQQJv',
  'ZCnRCDwRWCPrTrsW',
  'HwRNLLsnHRNjtRSqNqMmfqVVMbqg',
  'slqwzGvWqMsvbmTzTCBhhBhgcgjbCPCchc',
  'tJVJSZStQdMQSdntJHjFNFPCNpjFCPcFFdhB',
  'QDrRVZSnrQDVVRRtRHHWGmzTDDqMqMfzwswWsl',
  'rFBrJFcrWHzCLFHqSg',
  'PdVjfjlGPRzRGtGLRC',
  'TQPMpMVPDDPfPTMMPpTWWrhbcbTcWbzzcsmTmb',
  'ZDQDZDJNqqNbwQPgtlGntHlVGlPPrf',
  'vhmChcgvMCdvzCvvHfdntBHGBldrHBVG',
  'cCpTCLvmjhpjzSTTLSpwbDqjJQFZgNDwJssFDw',
  'LfMFLwMwdrFmWBJD',
  'tVlHqqVTHRtmQggrjQqDJg',
  'VDntHnDGRntHPbLPPLLZhcsLPLww',
  'FBLddLctDQcbCLltbdCRdLQVNVDjnPHVnsjnPqVSHNNVTP',
  'vGmwrZZWJpfWfmvZgZJjSTPqsTrVPTrHTssNPP',
  'wNZJffhNWmhvMhgwMZpvNJtbQRtQQLdFhbQFClLBCBlc',
  'npvSWJBCDDBBDSvCZSpJdsTZsRhTdgMgPdhqHHqR',
  'bjtwqLrtmfmtLVjVLQHHHdgwTTHMssMTGHhH',
  'VtmVVNtqlllpJvnnnS',
  'nCqrnLSSGnpjBjBGbcbPbB',
  'vfdVdtdgMMrFgHfHPcBcPBjwQDjFbwDB',
  'zgHWMmgHmWfWvVvRRzLCSCJsZNpJZSsrnssW',
  'bBjWlfrrnClSssMMFmVVhMjgMpLM',
  'dRDqDdzQrDdhqMMPtVLgFL',
  'THDRwHDNDdQdcDvTcZbBGBGrZZnZcrlb',
  'jgSVPVsVmshhsCQm',
  'vmFtcDBfDFLrvTFZvLFvWzWhHwCWHnwHnCQCcwnq',
  'FmDpFBmZZFrDbDfDtmLNgMPNGdPjRdPlPPpMVN',
  'VVJGdSHZnnHdgFntcschhccvvPvtstPq',
  'mLNjNQFBpPlPvNqs',
  'LMTMMRDwwMMSGZzRnnGbzF',
  'JFFfVrvVmHfGmHFvmrSQBQlSJLlShLlgBqwJ',
  'DMCdpCbtgbcCCNpbCCPgRqdldBRQRBRwLsBSLhQs',
  'cgbcPbpcWDWjNCZDWWZttDDGrHzznHzjGzmHnVjVvvVnrz',
  'rtGTmSTGNtvvgfNGSbfwWWvJqwcDwwJPWcwWqD',
  'lZhdHzFhLZhdBcWsWsWmwPcFqW',
  'BhhjLzhZCCdhgCTtCSMmMrbt',
  'FrzSRNrWNFdNhcRDDdrFWCVVZZZmjJbJSPlllgllVbgT',
  'nQGGHqvHMVVpMLGffqtwLMtwlmPbTbjZPJmllLJBmZmZlZbP',
  'VMvvpvQttHqnsvhhzhdrcdWNchsW',
  'BzRTBbWVQNdngtDFVprDFrpF',
  'vhfhSJvbhwSpDDFZHfMpHp',
  'JhmvJsLLJLJqmsJLbsGGjvNRzzBcTBNlRNmnRTQdzzzn',
  'vpCLrTcpRmncrncLcnccvLLNWVsRbhbtsQbJbVQWtWlWbW',
  'PfFfdjdSjPffMFsQbNhlFssFNQ',
  'zBDsjgfZHczLHTHC',
  'BnvpJnVgPWJzczpnvnWVWRGTrRTGmmBhRmBmThrmrf',
  'dNlwjLNLlbLSjLQVdLdjjSTRHmRmTTNmmRRtfTTfhThs',
  'FSSSqbVDQZzzPPPFZc',
  'fTTrrBqwfDTWfTDrRNrnRjgPSpJPnnmp',
  'PvHPbsvZlMtbbvbCLLMHtHZZjtgJRjSnJSpSpjRgRjggSRmn',
  'VLHbCbVPLZvlvMhHCHlPHbLCqQQfdQTBddTWhDTBchQzQwBW',
  'ZBHHfHWLfLqjfLjHZBSDwHDWhvpFCQqNpvVNVNQCFPJvPQCF',
  'zMrtclbdvFPSpdFp',
  'rGMMnnGgsbzblRnlSrzSgRRDwLWjLjTTDBZmfLwZmDBf',
  'rfJVfnztTfZFMfZq',
  'cRGcdddPRbHvHCRHRmShqFrPSTmTPjSjZT',
  'NvRHGGdNLrNJsDtL',
  'dgggppRqnlnjbbjRwzmtHb',
  'ZTPhrVvMZhrVQPZNCMZQjjbFtjmswwFtzVmLGbmL',
  'rZhPCPPcNPNTMfvZPCvhMPSBpgSqSqfpDgJJggdwWJgg',
  'TsgFbTQSZZsSJFThhggQFshpMSzRRRDPwwzPwDftRDrczLww',
  'GCmnjCNjmlVdHNfdGNjMwPrrLwLcMcrcRHzMHM',
  'nmmBnmlWlVWvjnNlpfFQbZsFpQhgJFpB',
  'jfpdTTqqJpDfQrscgsDh',
  'mNFmHHtVsVQrsllG',
  'CmFtZPHNzzpBspzpLBqw',
  'RsgJsjsZbTjmZZMMJPtCSPPDhCSrDhrjhC',
  'lBwzHLQddZlLQnChGdtDhrnqhq',
  'fLHpNQQpwvHllQVQHNNfHpzZMFWbccmTcbJMcFsWTRVbsTWF',
  'DhHFMRDDmLmshTmSCpSWZVNHtCCNnW',
  'fJJPBvlvlBflQQfQtNWtQzpSWZNtCZpN',
  'vPJbdvBfqhqhShTFMs',
  'lttWShphLtWWGppCQLlwZTHZHmfjjvwvHFmw',
  'MFNssMMDVzrrnTmvJTHwJmZmZr',
  'MsBznNznRgzzncFBLQQGGBBtdhdGpWPp',
  'JFmvMWBmBlbBCZrZrH',
  'DjRRjgffgjqwsDqrcHNNbCZbCbbN',
  'sSffwRVjjDVzfjSjswDSQLdPrvGvFMmMJMMJmnWzGL',
  'RbvwgbTVgzGTrhvWDmNDGJfCDffMmNBD',
  'PjSlqldccqFLSqQLCpJfpWDCcCJZBpMD',
  'jlHdPlqqSnjHggWgwrhzRz',
  'WsJnWnmCJpTnLWmJLCSDVVmhNjRbrDRgrgZRhrjrhhgdZN',
  'QlFfQBqlBwBqBffMFPsbgdgwsrZjrPNrNs',
  'MvvvlHBcfBtvffGBcMqqqLpmLsJtpSLSCWCVCnnTzJ',
  'QSRRwSWPhWhwwHbtsNGZNRNZTgRcmc',
  'nfvDCrnnDvJJDDVMLNgtsZmZsVtZGgqmGp',
  'nCngDlFfvvJLnCJJLMFMClHBBzQzwzbhlQHHPllbBhdb',
  'qNFzGFFFnGGDJnzSdFdzjdvmCvzPzzRmgCmMmtgvcmtV',
  'sQlhpLpWQQZpQZpQrBlLsLLCRggtMgVbbtggBmVVmbmBVm',
  'ppQHRflRSGTdHSGN',
  'BgTnWbbwPgPWgPGfGlWfdFFFlsSF',
  'QvDNDZRMjCNZcHZZDQFShGFpBhdRsGpLsFRd',
  'rrqvNcHjBcJgrTzbPVVz',
  'pCjdsSdCljdBlpJpdmjHFHmDfTDTwgfgcw',
  'WQrWnGzhNZzWfcnHfBwnvwHc',
  'RLGNGQhWZhMrZNtBpsLPsVJbPLVb',
  'TRDDSzNhHNHfSppCCMZsMMssdgZvfZ',
  'GbGlctGqrBqVtrtLGtmqTtssPdMZcCZMnMvCZgdddgsP',
  'BQqbVVVqLtBqWbTlmLBhQjFhJDRpHhzpJSJDNF',
  'FTHTnPSmFqSPCTVDhZRCZDhjDRsV',
  'blbLcBgMgMlrcLMbzrlBLZjRVsZZfNVfVfJsbNqDDh',
  'tLtLQgzWMzSnHmPSWdqW',
  'DnwmFcpmpGqFwCwmfCDMZsNVVMdlVrsNsczrrl',
  'ghtBPJbHtWPbJPdBSPMzsrTTzZMTTMSNzrVZ',
  'bPdjjhtPPJjjBQJJdbhRgJhLCnfLGGmLnGLpLfDRGGfpqG',
  'HzzZZjCLjjZCmVQppssbGpmcTGgp',
  'nMnJPqJlMPqBJllSJvlMSDGGBcgBcsfBhTpsFhgTTfFQ',
  'drSRqnSqJDcSJrMJnRvCHtWZtjZZrHtVjrwZLj',
  'mDJjmQggstPvDWJgQWJgPPmNFFLZpphZNlNpZLhSLvLZNf',
  'rzzfTczCzCdBwddcCCHFpHFMNHZSHMFrHNFp',
  'bcfzdGnCtVsVtsWn',
  'CMfCfGfwbMMLdTMH',
  'lqzDgLWqQWhQNWnlQqHTFFFFchbddTRbSddd',
  'WnzDNZmPZmgglNCrvjrtrLffrJZJ',
  'BllCMzjjlBHCCllHvljCMhbrQbTVTrvprTqrFWFFvF',
  'ZNwfNLRnfwtRtNwqThVFpwWVJrbh',
  'LnRnpNRSLcpZZNtmZmjgGgGMPBHCmMzsmsHM',
  'MRMPpwWTLMMMMLLRMPbvfQZCnqQnqvWZWGqGDQ',
  'gJslgmlmSZqssGGbnV',
  'mJFSmmjcdmgJhdgrdjcdjwbRwpMwpHBRHrztwtRMRL',
  'CccctqnQVvQcrsFwznmnrBrs',
  'LLPThTSjPdJjLTtMBrsDmbbsBwbswGMF',
  'jLSLWPLlTlgSlgSghdvtQZvqvWRcCpHVCqWp',
  'DmggMZCDbdNrttnbPn',
  'cclqSqGjSBwLqswNrFNzffFfNPsCsd',
  'jGpLBcwlQBSpLjSQLvjRTZHTCRRDggRTHhmvmV',
  'LWzrnwZFnzQlWQZndWFNvHBNDVBBNjplNjjVvV',
  'RCSmPSCgsgTmCRqnsTCHvjJJpvBBSVSMpVjVMJ',
  'sfgsRGnRTghQWWbLwfhF',
  'JnJlTnDnwtWHMdJt',
  'phNPDPVvPcPPvMRqVZRWMqRRWM',
  'fGGScQDfssQzLbgT',
  'rLVVdSSvVzQSRnzSRRnBQMJqDTjMsMsMqqPPhP',
  'wmbWWFGVlGfptbhshsTmhqDPJJMm',
  'CbWtWlCNpglgbtCWtFHdvNHVZnZZVnNVHHcc',
  'qtRszqSZVnTCVwwLJpcgppLHqp',
  'MPvBGNnDWMGMPDvGBPvMBFvpppjHwHpJJJJJFjjwLcjLJg',
  'hBfPNvGvhDnvMPdslCZCtVsRRCSZff',
  'HgvgvLNDcCcNBPDDvNNBzLNBnnhQqwRnRLQhWRhhWssqsnZZ',
  'FlfprJzttrrTlGpbJVQhRwwbnbsRWVnZss',
  'FGmdJrFdJddmjFfTttpfftlDvHSDgCDHgvSgHPcBzMHSzj',
  'dgHhCJbBbwgNcVzlvzvzQVzH',
  'RZPjRRRDPnjrjSnfFrDsnvzWVlzLfGzvBVWccclcGl',
  'nDDZPjjRnZmFstnZBrsZgtCgbtMdqbJdNqMdgdwg',
  'LvdrGnDBGBGrvrGLJtdrmmcfClqllsqlmjsLmcQC',
  'VpbwbwTSVVwpzZMRSVmsjDqCclclNZCjNjQq',
  'PpzWwRMwTwFpwtJBHnhtdnDvvP',
  'GCJSClmwzmSgrpPpSpgcrS',
  'bjLpsspHMHvBTsDLjTDtbTBFRFrQQQPcgQgcFcFPcFcnPs',
  'pBTBvqBHbDjHfJqlGlzWJGllWC',
  'GgbGNjQGzzQvFcFfRFmFJbff',
  'pHDSLLCqpqppPZVSCSDdncRFwfmZcRWRJfncmRJn',
  'LDTTLSSDSMQgvNTmzz',
  'bLjgLVlJnjSJjgLgLjqqMcMfddftcCCnCccfQfsC',
  'FRRmphNRmmdwPHpBPswDftDzMCfMcfWMMC',
  'FrvdvrPPFHhNRPvFRmFZVbggqbGjJglJbjjTrVjJ',
  'cSpdczpfRQQGNGGqvGHv',
  'wPwFPhCFWbbmChwWmhFPsWrsDVwqVqZqvVVVvzGHDZqHqtZz',
  'gbPznCbPmmWrWbWhJRpLnLRnTcScRSSLBd',
  'pfwbrjTbDczbzbPcwTQbvWdWWTdddSldVHWSgHgn',
  'mQmFQRFssJJJJthtJmBJmCHMdlWdnlltnHSVlSlgtnvM',
  'BJBhRhRqRLRJNhJhBDwjzPPPcNQZrZrzDr',
  'HTHwQJzwLZNcTwJtFRFHDtFvRFRFdr',
  'jlMnMlbqqpMBvsWBVGRRGdSVgrDthFDddh',
  'qvMjjMMpbPWqmMjnlpplpnWscNwLCQPzQLfzTzcZJfLQLPJz',
  'gCTHTVdPdPvFfdCCSScZSZncMMCGGM',
  'LNqLlssmWlLqzBRzWBwWBRRZdmJZcSSQDncnJtQcGDDDMd',
  'jszNLwNWRRrzNbhbvHpdTjdvfH',
  'NgDWhQmhfFlWFWlzDfhpBwfPBBdwwBJRBPqJJB',
  'HHMCcHtGcMMbSGjScMGLSsRnqdJJlqqpCPJBRpBRdp',
  'trMtLVtjjVtjttGctrLLTlZmgFzZTZzZNQmzZDNFhgFD',
  'MBMtFzBnzSJJttSZBNNZfTsPqTqqqNZNPc',
  'LlQDQLVCwCDbfRCmRGVjCwLLcqslNcNPgqgTPTsqNNsvqHqs',
  'RfffRmdjnnzpndtr',
  'nzpnDRDVwRRjVTSlTtlSSCQLDC',
  'vgZHFBbbfCbvFbrFSSTqqcGtGTtBGQqS',
  'HggMfPfbFZbPvNvgZZdHsnJjCzphzVwJjsmpmjMw',
  'FgvgrgDpRDGTTWVDVd',
  'zmbnNhHHQHshhhcbnHnnbBTMBMLLWLLGMqWLfzLLTV',
  'mnnQHjcHHJmnNcHnnhmvZpRrCVZVZFrRJZVPFr',
  'ZhpVhCSHbsCPbnmF',
  'GBWGGrftTJlrfttQqsVPbPnGjDszFVncsG',
  'qfMlQJWBrNWQfftqrQqBhRvdVVSNVSpZdvSZwZRS',
  'mfzRQqMrtCwLMMZM',
  'sbVbWgFdJCldtNRPNZ',
  'FpggcgsjJccJVJJJcbbWWGrHnfmBnrHzfnfzvqrQmpfR',
  'rWvbrfLnHHnzlFrFWWzJfRQQTwbwRQmQQCgQTwQBwg',
  'MPsqcZpZdpjGMptpqCSsSwRNjQTBhgwhmgwgmmwgBm',
  'SZqqqCDGMtpMFFDvFHfJlvDJ',
  'RZnrZLZbLjRZwdlrnbLClCHMNCTlMMWBPPTHlT',
  'SDgDzQDcfzJBNPssWCwSMN',
  'fpQJwmmQmjhjGRbr',
  'jQzqvLzvMTTQMMSS',
  'VJlSrnBRZbbJbVnWWBlVWRCSNTMppMBMmmNPHMcNBmTMGmHp',
  'CtDZJllRClbFzLtszhqFqS',
  'VwcwzBdmMzJSdMBzzGndGSmlbqbgZgfblTJrTbrqZbTlTb',
  'tRDvCvCRDCDWtPjCHjvDWTgZLfNqclZTTrNfZtLbLc',
  'DDvPhhRRvjFjHPRjvVdMwhnpwBSGcwSGcc',
  'LRtLJSNLdNLjNLRRNdRzVmVrggWmmmpVmpVvBBWFvm',
  'wqfZnsMnhCnlfGPCCqwphJpWrFHBWHrvTrTHTH',
  'ZsbGsflwGtjJbzLLjt',
  'MjdFCjzsQFJQjzbmWHHLPPTfvsLfPZ',
  'cNgpBgplzVvPTvmLPTVm',
  'qNlqpcNtBzjQQCQqJjwJ',
  'cczNGcgNhztlGPCCLDpBSpfVDpCJpSpBWs',
  'nFqnwrRQrHnFHTMnZqQwMnmFsVsfbSSSJBSsfVVDfWVBWbVm',
  'RRFZFMHjrQMjrHZqRjLdchdGtGjzDLgtzN',
  'tzFmNfFNmFclrffhNtNlDWRSdFWnJCnRvRjvJvjD',
  'LMgZgpZLMpPPPVPMMPbjbndWJSnWbWHWSCRbJD',
  'BLwMpgMPgwQpTgTTpMVZMTftcGhhhtrhhcGGzQhsllCN',
  'DWtHFWDHtwsWFHWDWwQblVgnllRBnjvBlVjRVbll',
  'TzChCMGfNhZSLhLhzRRVvvjmczRgvRmv',
  'pZSGpNJhCNGLSNLfMGJfJJQFrDDQDqHHgHpsWPFDttQW',
  'qqccVQZWBVfjzzPVDMJtDtNccCgmtCCm',
  'lvBRHBRGRDDCRmnmbD',
  'SLFpGTSsTSsLFsHGvLvdGvdVwZBzZqqzjdQdZjVfrqwW',
  'dLLwHLTWwjMLRZHCHZglDvjgvvNNDssSsmmN',
  'nPfJPFbnhMJQfnpJGQJfQBBVssglsmsVVmBDsSqDgvNlgv',
  'FbMrPPhrtGbJpnhJpJFFbbpJcwtdZzHZZwHCZdwctzTLcHTw',
  'hCfzfLVbShRwRlBjdzmz',
  'JZhrMMhZgvHFHJnHGgWdpmpnmlpRwBndRBwcBj',
  'rMHFhgHZqtGvrWsbPfPNSbstTffN',
  'dSwQQdSlHtlVQtqqrMZbFBRnBfZRMbDwMw',
  'GTpcgLcvWvGvJzGpZGJpWpfmMWPBmDPRFPMFMmBfbFFW',
  'hpcGhTCsGspLchGGzcpvZNStQHSSlNjjtlttlQsq',
  'nJlhHlLlJGlRnMSsMLsnsSMwFHgwrTBFFwjBjppgpqfwqf',
  'QmzzmbzNcZQQzDVZDcZQNDtzRqRBFTqTjjwpjBBNRrpBwfww',
  'mvQPbQtttVVDzvzmRWCWLhSSslvWLGlW',
  'nSpdSDPpRdrNBhMBMSJJ',
  'bzCTcwzbczCZswMssczmCCgcqBmrQrrmBmqJBVBVNtrVttrq',
  'cvzscgZzwTCsWsZvwTfzljDHnflMGMMndHFDdRPp',
  'sDDnzLVnsMtjnDgfSSbfBjggbqBC',
  'rlrlcppWcGdPrZNccJrSBSmCHqbSqCbSCgCHPq',
  'NWcZgpFFgFpDFnDvtMDFzz',
  'ZpczTjpZcnncHFDn',
  'hSqqJWWWRRhlnFDVSFnQCB',
  'qhNMWfqfMhJJRLRvppDzNZTpPTvwwD',
  'rbSDCwPWwPVcSHcwHspNpNsddszmwGtswN',
  'vBBfgQvBMvMvjLLlllqtBTNNTPPzTztTsRNPTt',
  'vvQnjlMjjjqJqQLSrcDcPWbcHbDrDn',
  'BphwqbwNsjsNsBdDjjhGpsGWzMMTWRTCflfDWSSzfzSlWf',
  'cFnrrHrnZVZQQvFFVvZhRzTCWlSRMSWhZMWt',
  'HvJVvggHvVrmQLqmNqLBbhsssw',
  'NcBqSjGGBjNbZcHwhRVHPwPwPlZR',
  'TvdtdtvFgHwWgdhn',
  'tMJFTvtvFtrLJMHBqNNBzjrQcjqNmB',
  'RrQfLfQvMFdQvLLQVfFcnbSbnwVSnbDslsbSDzDD',
  'PHLjmHqqZCjPglsbwJbqnDbbJl',
  'LNHLhjBHHGRfphphrtfh',
  'FcdMchqcgdchqcfcNWWghNrRrVRjGHFjDJmGFDrRVGJD',
  'zQtvBvtbQzpSzBptzbBznnwZJRDRVmVnGRGrDrHjZGrr',
  'HLspTpQLBqWqLqcNgM',
  'rnqbSSQhsshFqQQnsPSnhbnrzHzzHLNvLHCLFCvVJTlNLJTz',
  'fcffljGBwgmwwftzNdCCdvLvtHNLTH',
  'BjWgMGjjWZMwjjgwgMWpwPlnnqSnqQhnrbPMRDsqQs',
  'hRJhFdNJcrbqbbMF',
  'qZlTTgTvlHnqvllPssQrgQcQwscrQMsf',
  'CClpSnTllZnZCDLHnlNzGSRmRthVmmzqJzhd',
  'DLzSMtDLtzmmlDlMlMDbcrcTDqFvVvVqqTbD',
  'dnZshHpZRChgnszRwRZCpTqqTcwVqFcrVqcBVPqVTr',
  'snRRRdJsZgphCWlWtmJSjWWzjt'
];

const tests = [
  'vJrwpWtwJgWrhcsFMMfFFhFp',
  'jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL',
  'PmmdzqPrVvPwwTWBwg',
  'wMqvLMZHhHMvwLHjbvcjnnSBnvTQFn',
  'ttgJtRGJQctTZtZT',
  'CrZsJsPPZsGzwwsLwLmpwMDw'
];

let totalPoints = 0;
// ==================== Puzzle 2 ====================

for (let i = 0; i < strs.length; i = i + 3) {
  const first = [...strs[i]];
  const second = [...strs[i + 1]];
  const third = [...strs[i + 2]];
  let found = false;

  for (const char of first) {
    if (second.includes(char) && third.includes(char) && !found) {
      found = true;
      const ascii = char.charCodeAt(0);
      if (ascii >= 97) {
        totalPoints += ascii - 96;
      } else {
        totalPoints += ascii - 64 + 26;
      }
    }
  }
}

console.log(totalPoints);

// ==================== Puzzle 1 ====================
// for (const str of strs) {
//   const str1 = str.substring(0, str.length / 2);
//   const str2 = str.substring(str.length / 2);

//   const common = findCommon(str1, str2);

//   const ascii = common.charCodeAt(0);

//   // calculating the total points
//   // note: this function can be improved. here i am assuming there will be no chars other than alphabets.
//   // if present, then the checks needs to be more precise.
//   if (ascii >= 97) {
//     totalPoints += ascii - 96;
//   } else {
//     totalPoints += ascii - 64 + 26; // is there a better way to get this? this feels a bit crude, but it works. so ...
//   }
// }

// console.log(totalPoints); // 7863

// // function to find the common in both the string
// function findCommon(str1, str2) {
//   let commonMap = new Map();

//   for (let i = 0; i < str1.length; i++) {
//     if (!commonMap.has(str1[i])) commonMap.set(str1[i], 0);
//   }

//   for (let i = 0; i < str2.length; i++) {
//     if (commonMap.has(str2[i])) return str2[i];
//   }
// }
